"""Named CSV artifact catalog."""

from __future__ import annotations


SIMULATION_STREAMS_CSV = "simulation_streams.csv"
SIMULATION_DETAILS_CSV = "simulation_frame_hops.csv"
SIMULATION_FRAME_RELEASE_TRACE_CSV = "frame_release_trace.csv"
SIMULATION_ENQUEUE_TRACE_CSV = "enqueue_trace.csv"
SIMULATION_TRANSMISSION_TRACE_CSV = "transmission_trace.csv"
SIMULATION_FORWARDING_TRACE_CSV = "forwarding_trace.csv"
SIMULATION_DELIVERY_TRACE_CSV = "delivery_trace.csv"
SIMULATION_RESPONSE_TIME_TRACE_CSV = "response_time_trace.csv"
SIMULATION_CREDIT_TRACE_CSV = "credit_trace.csv"
SIMULATION_SCHEDULER_DECISION_TRACE_CSV = "scheduler_decision_trace.csv"
SIMULATION_STREAM_SUMMARY_CSV = "stream_summary.csv"
SIMULATION_HOP_SUMMARY_CSV = "hop_summary.csv"
SIMULATION_QUEUE_SUMMARY_CSV = "queue_summary.csv"
SIMULATION_RUN_SUMMARY_CSV = "run_summary.csv"
ANALYSIS_STREAMS_CSV = "analysis_streams.csv"
ANALYSIS_DETAILS_CSV = "analysis_link_breakdown.csv"
ANALYSIS_STREAM_WCRT_SUMMARY_CSV = "stream_wcrt_summary.csv"
ANALYSIS_PER_LINK_WCRT_SUMMARY_CSV = "per_link_wcrt_summary.csv"
ANALYSIS_LINK_INTERFERENCE_TRACE_CSV = "link_interference_trace.csv"
ANALYSIS_SAME_PRIORITY_TRACE_CSV = "same_priority_trace.csv"
ANALYSIS_CREDIT_RECOVERY_TRACE_CSV = "credit_recovery_trace.csv"
ANALYSIS_LOWER_PRIORITY_TRACE_CSV = "lower_priority_trace.csv"
ANALYSIS_HIGHER_PRIORITY_TRACE_CSV = "higher_priority_trace.csv"
ANALYSIS_PER_LINK_FORMULA_TRACE_CSV = "per_link_formula_trace.csv"
ANALYSIS_END_TO_END_ACCUMULATION_TRACE_CSV = "end_to_end_accumulation_trace.csv"
ANALYSIS_RUN_SUMMARY_CSV = "run_summary.csv"
COMPARISON_STREAMS_CSV = "comparison_streams.csv"
COMPARISON_SUMMARY_CSV = "comparison_summary.csv"
